cart/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
    path("",views.cart_page,name="cart"),
    path("add-cart/",views.add_cart,name="add_cart"),
    path("delete-cart/",views.delete_item,name="delete_cart"),
    path("update-cart/",views.update_cart,name="update_cart"),
    path("clear-cart/",views.clear_cart,name="clear_cart"),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("shop.urls")),
    path("account/",include("accounts.urls")),
    path("cart/",include("cart.urls")),
    path("payment/",include("payment.urls")),
    path("dashboard/",include("dashboard.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
    path("",views.home, name="home"),
    path("product/<str:slug>/",views.product_page, name="product"),
    path("shop/",views.shop_page,name="shop"),
    path("category/<str:name>/",views.category_page,name="category"),
    path("sale/",views.sale_page,name="sale_products"),
    path("add-wish/",views.wished_product,name="add_wish"),
    path("dis-wish/",views.dis_wished,name="dis_wish"),
    path("search/",views.search,name="search")
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
import random

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="upload/images/category/")
    
    description = models.TextField(blank=True,null=True) 
    
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    mini_description = models.TextField()
    factory = models.CharField(max_length=255)
    image = models.ImageField(upload_to="upload/images/product")
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    slug = models.SlugField(unique=True,blank=True,null=True)
    
    count_rating = models.IntegerField(default=0)
    
    price = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)
    is_sale = models.BooleanField(default=False)
    
    @property
    def sale_price(self):
        if self.is_sale:
            sale_p = self.price - (self.price * self.discount / 100)
            return sale_p
    
    @property
    def rating(self):
        count_rate = Comment.objects.filter(product_id = self.id).count()
        if count_rate != 0 :
            return self.count_rating / count_rate
        else:
            return 0
    
    def save(self,*args,**kwags):
        super().save(*args,*kwags)
        
        if not self.slug:
            random_num = random.randint(10000,99999)
            self.slug = str(self.name) + str(self.factory) + str(random_num)
            self.save()
    
    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"
        
    def __str__(self):
        return self.name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="upload/images/product")
    
    def __str__(self):
        return super().__str__()
        
    

class ProductDetail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_detailname = models.CharField(max_length=50)
    product_detail = models.CharField(max_length=200)
    
    def __str__(self):
        return f"{self.product_detailname} : {self.product_detail}"

class ProductFeature(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    feature = models.CharField(max_length=255)
    
    def __str__(self):
        return super().__str__()

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=40)
    comment = models.TextField()
    
    rating = models.IntegerField(default=5)
    
    date_created = models.DateTimeField(auto_now_add=True)
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        product = Product.objects.get(id=self.product.id) 
        product.count_rating += self.rating
        product.save()
    
    def __str__(self):
        return self.user.username
    
    
class WishedProduct(models.Model):
    product = models.ForeignKey(Product, on_delete= models.CASCADE)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    
    def __str__(self):
        return f"{self.id}"

shop/views.py
from django.shortcuts import get_object_or_404, render , redirect 
from django.urls import reverse
from django.http import Http404 , HttpResponse , JsonResponse
from .models import Product , Category , WishedProduct
from .froms import CommentForm
from django.utils.safestring import mark_safe
from django.db.models import Q 

# Create your views here.

def home(request):
    products = Product.objects.all().order_by("-count_rating")[:10]
    products_discount = Product.objects.all().order_by("-discount")[:12]
    return render(request, "shop/home.html",{"products":products,"d_products":products_discount})


def product_page(request, slug):
    product = Product.objects.filter(slug = slug).first()
    
    if product is not None:
        
        if request.method == 'POST':
            if request.user.is_authenticated:
                form = CommentForm(request.POST)
                if form.is_valid():
                    form.instance.product = product
                    form.instance.user = request.user
                    form.instance.rating = int(request.POST.get("rating"))
                    form.save()
                    return redirect(reverse("product",args=[product.slug]))
            else:
                return redirect("login")
        
        product.mini_description = mark_safe(product.mini_description)
    
        return render(request,"shop/product.html",{"product":product})
    
    else:
        return HttpResponse("not found")
    
    

def shop_page(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    phones = Product.objects.filter(category__name = "phone")[:10]
    tvs = Product.objects.filter(category__name = "tv")[:10]
    laptops = Product.objects.filter(category__name = "laptop")[:10]
    return render(request,"shop/shop.html",{"products":products,"categories":categories,"phones":phones,"laptops":laptops,"tvs":tvs})

def category_page(request,name):
    category = get_object_or_404(Category,name=name)
    
    return render(request,"shop/category.html",{"category":category})


def sale_page(request):
    products = Product.objects.all().order_by("-discount")
    
    return render(request,"shop/sale_page.html",{"products":products})

def wished_product(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            if request.POST.get("action") == "post":
                product_id = request.POST.get("prId")
                
                product = Product.objects.filter(id = product_id).first()
                
                if product is not None:
                    wished = WishedProduct.objects.filter(product = product, user=request.user).first()
                    if wished is None:
                        WishedProduct.objects.create(product = product,user = request.user) 
                    
                        return JsonResponse({"message":"success"})
    
    return JsonResponse({"message":"nothing"})

def dis_wished(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            if request.POST.get("action") == "post":
                wished_id = request.POST.get("prId")
                
                wished = WishedProduct.objects.filter(id=wished_id).first()
                
                if wished is not None:
                    wished.delete()
                    
                    return JsonResponse({"message":"success"})
    
    return JsonResponse({"message":"nothing"})

def search(request):
    search = request.GET.get("search")
    
    if search is not None:
    
        searcheds = Product.objects.filter(Q(name__contains = search )| Q(category__name__contains = search) | Q(mini_description__contains = search) | Q(factory__contains = search))
        
        return render(request,"shop/search.html",{"searcheds":searcheds,"search":search})
    
    return redirect("home")

templates/shop/category.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    
    {% comment %} <div class="container w-100">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-12 col-lg-7">
                <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner rounded shadow-light">
                    <div class="carousel-item active">
                    <img src="{% static 'images/banner-large-1.jpg' %}" class="d-block w-100 rounded" alt="...">
                        <div class="carousel-caption ">
                            <h5 class="d-none d-md-block">First slide label</h5>
                            <p class="text-light d-none d-md-block">Some representative placeholder content for the first slide.</p>
                            <a href="#" class="btn btn-danger rounded">go to page</a>
                        </div>
                    </div>
                    <div class="carousel-item">
                    <img src="{% static 'images/banner-large-2.jpg' %}" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>First slide label</h5>
                            <p class="text-light">Some representative placeholder content for the first slide.</p>
                            <a href="#" class="btn btn-danger rounded">go to page</a>
                        </div>
                    </div>
                    <div class="carousel-item">
                    <img src="{% static 'images/banner-large-3.jpg' %}" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>First slide label</h5>
                            <p class="text-light">Some representative placeholder content for the first slide.</p>
                            <a href="#" class="btn btn-danger rounded">go to page</a>
                        </div>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
                </div>
            </div>
        </div>
    </div> {% endcomment %}

<section id="new-arrival"
    class="new-arrival py-5">
    <div class="container-fluid">
      <div class="d-flex flex-wrap justify-content-between align-items-center mt-5 mb-3">
        <h4 class="text-uppercase">Newest</h4>
      </div>

      <div data-aos="fade-in" class="overflow-x-auto">
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-5 d-flex flex-nowrap">
          
          
          {% for product in category.product_set.all %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            {% comment %} <div class="d-flex justify-content-between align-items-start mb-3">
                                <img src="{% static 'images/product-small-1.jpg' %}" alt="Product" class="img-fluid product-image" style="max-height: 150px;">
                                <button class="btn btn-link text-danger p-0">
                                <i class="bi bi-heart-fill"></i>
                                </button>
                            </div> {% endcomment %}
                            <div class="image-holder position-relative">
                                <a href="{% url 'product' product.slug %}">
                                <img src="{{product.image.url}}" alt="categories" class="product-image rounded img-fluid">
                                
                                <div class="rating">
                                    {% if product.rating > 0 %}
                                        {% with " "|center:product.rating as range %}
                                            {% for _ in range %}
                                                <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-solid"></use></svg>
                                            {% endfor %}
                                        {% endwith %}
                                    {% else %}
                                        <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                                        <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                                        <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                                        <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                                        <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                                    {% endif %}
                                </div>
                                </a>
                            </div>
                            <h5 class="card-title">{{product.name}}</h5>
                            
                            {% if product.is_sale %}
                                <p class="card-text text-muted">${{product.sale_price}}</p>
                            {% else %}
                                <p class="card-text text-muted">${{product.price}}</p>
                            {% endif %}
                                
                            <button data-index="{{product.id}}" class="btn btn-primary w-100 add-cart-mini">Add to Cart</button>
                        </div>
                    </div>
                </div>
          {% endfor %}
            
            
        </div>
      </div>
    </div>
</section>

<section id="best-sellers"
    class="best-sellers py-5 mb-5">
    <div class="container-fluid">
      <div class="d-flex flex-wrap justify-content-between align-items-center mt-5 mb-3">
        <h4 class="text-uppercase">All Product</h4>
      </div>

      <div data-aos="fade-in">
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4">
          {% for prod in category.product_set.all %}
            <div class="col">
                <div class="product-item hover-effect-slide">
                <div class="image-holder position-relative">
                    <a href="single-product.html">
                    <img src="{{prod.image.url}}" alt="product" class="product-image img-fluid">
                    </a>
                    <button data-index="{{product.id}}" class="btn btn-primary w-100 mt-2 rounded-1 add-cart-mini">Add to cart</button>
                </div>
                <div class="product-content d-flex flex-column flex-md-row justify-content-between align-items-md-center">
                    <h5 class="fs-5 mt-3">
                    <a href="{% url 'product' prod.slug %}">{{prod.name}}</a>
                    </h5>
                    {% if prod.is_sale %}
                        <a class="text-decoration-none"><span>${{prod.sale_price}}</span></a>
                    {% else %}
                        <a class="text-decoration-none"><span>${{prod.price}}</span></a>
                    {% endif %}
                    
                </div>
                </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

  
{% endblock content %}
    

templates/shop/home.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
<section>
    <div class="container-fluid">
      <div class="slideshow slide-in arrow-absolute text-white" style="height: 80vh;">
        <div class="swiper-wrapper">
          <div class="swiper-slide jarallax">
            <img src="{% static 'images/lapban1.jpg' %}" class="jarallax-img" alt="slideshow">
            <div class="banner-content w-100">
              <div class="container">
                <div class="row">
                  <div class="col-md-10 pt-5">
                    <h2 class="display-1 ls-0 mt-5 pt-5 txt-fx slide-up ">LAPTOP</h2>
                    <h2 class="pb-1 ">Buy now</h2>
                    <a href="{% url 'category' 'laptop' %}" class="btn btn-outline-dark text-uppercase rounded-3 px-4 py-3 mt-3">Shop Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="swiper-slide jarallax">
            
            <img src="{% static 'images/banwatch1.jpg' %}" class="jarallax-img" alt="slideshow">
            <div class="banner-content w-100">
              <div class="container d-flex justify-content-end">
                <div class="row justify-content-end">
                  <div class="col-md-10 pt-5">
                    <h2 class="display-1 ls-0 mt-5 pt-5 txt-fx slide-up text-black" style="margin-left: 560px !important;">SMART WATCH </h2>
                    <h2 class="text-black" style="margin-left: 560px !important;">Buy now your watch</h2>
                    <a href="{% url 'category' 'watch' %}" class="btn btn-outline-dark text-uppercase rounded-3 px-4 py-3 mt-3" style="margin-left: 560px !important;">Shop Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="swiper-slide jarallax">
            <img src="{% static 'images/ban-1.jpg' %}" class="jarallax-img" alt="slideshow">
            <div class="banner-content w-100">
              <div class="container">
                <div class="row">
                  <div class="col-md-10 pt-5">
                    <h2 class="display-1 ls-0 mt-5 pt-5 txt-fx slide-up text-black">PHONE</h2>
                    <h2 class="pb-1 text-black">Buy iphone or ... now</h2>
                    <a href="{% url 'category' 'phone' %}" class="btn btn-outline-dark text-uppercase  rounded-3 px-4 py-3 mt-5">Shop Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="swiper-pagination"></div>
        </div>
        <div class="pagination-wrapper position-absolute">
          <div class="container">
            <div class="slideshow-swiper-pagination"></div>
          </div>
        </div>
        <div class="icon-arrow icon-arrow-left text-white"><svg width="50" height="50" viewBox="0 0 24 24">
            <use xlink:href="#arrow-left"></use>
          </svg></div>
        <div class="icon-arrow icon-arrow-right text-white"><svg width="50" height="50" viewBox="0 0 24 24">
            <use xlink:href="#arrow-right"></use>
          </svg></div>
      </div>
    </div>
  </section>

  <section class="features" style="position:relative; margin-top: -100px; z-index: 2;">
    <div class="container-lg">
      <div class="bg-black p-5">
        <div class="row">
          <div class="col-md-3">
            <h4 class="element-title text-capitalize my-3">Book An Appointment</h4>
            <p>At imperdiet dui accumsan sit amet nulla risus est ultricies quis.</p>
          </div>
          <div class="col-md-3">
            <h4 class="element-title text-capitalize my-3">Pick up in store</h4>
            <p>At imperdiet dui accumsan sit amet nulla risus est ultricies quis.</p>
          </div>
          <div class="col-md-3">
            <h4 class="element-title text-capitalize my-3">Special packaging</h4>
            <p>At imperdiet dui accumsan sit amet nulla risus est ultricies quis.</p>
          </div>
          <div class="col-md-3">
            <h4 class="element-title text-capitalize my-3">free global returns</h4>
            <p>At imperdiet dui accumsan sit amet nulla risus est ultricies quis.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  <section class="py-5 my-5">
    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-md-10">
          <span class="text-primary text-uppercase">Welcome</span>
          <h2 class="fs-2 text-center">We're constantly testing new products, researching recent trends in the tech space, and updating our list of cool gadgets accordingly.</h2>
        </div>
      </div>
    </div>
  </section>

  <section class="categories overflow-hidden">
    <div class="container-fluid">
      <div class="row g-5">
        <div class="col-md-3">
          <span class="d-block py-3 text-white text-uppercase fs-7 ls-1">01. Personal Camputers</span>
          <div class="jarallax position-relative mb-4" style="height: 480px;">
            <img src="{% static 'images/category-thumb-4.jpg' %}" alt="categories" class="jarallax-img img-fluid">
            <div class="category-content position-absolute bottom-0 p-5 text-uppercase">
              <a href="shop-four-column-wide.html" class="text-white btn-link">Shop it Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <span class="d-block py-3 text-white text-uppercase fs-7 ls-1">02. Smart Phone</span>
          <div class="jarallax position-relative mb-3" style="height: 480px;">
            <img src="{% static 'images/category-thumb-2.jpg' %}" alt="categories" class="jarallax-img img-fluid">
            <div class="category-content position-absolute bottom-0 p-5 text-uppercase">
              <a href="{% url 'category' 'phone' %}" class="text-white btn-link">Shop it Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-5">
          <span class="d-block py-3 text-white text-uppercase fs-7 ls-1">03. Tv</span>
          <div class="jarallax position-relative mb-3" style="height: 480px;">
            <img src="{% static 'images/category-thumb-3.jpg' %}" alt="categories" class="jarallax-img img-fluid">
            <div class="category-content position-absolute bottom-0 p-5 text-uppercase">
              <a href="{% url 'category' 'tv' %}" class="text-white btn-link">Shop it Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <span class="d-block py-3 text-white text-uppercase fs-7 ls-1">04. Watch</span>
          <div class="jarallax position-relative mb-3" style="height: 480px;">
            <img src="{% static 'images/OIP.webp' %}" alt="categories" class="jarallax-img img-fluid">
            <div class="category-content position-absolute bottom-0 p-5 text-uppercase">
              <a href="{% url 'category' 'watch' %}" class="text-white btn-link">Shop it Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="new-arrival"
    class="new-arrival py-5">
    <div class="container-fluid">
      <div class="d-flex flex-wrap justify-content-between align-items-center mt-5 mb-3">
        <h4 class="text-uppercase">Our New Arrivals</h4>
        <a href="{% url 'shop' %}" class="btn-link">View All Products</a>
      </div>

      <div data-aos="fade-in">
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-5">
          
          {% for product in products %}
            <div class="col">
              <div class="product-item hover-effect-slide">
                <div class="image-holder position-relative">
                  <a href="{% url 'product' product.slug %}">
                    <img src="{{ product.image.url }}" alt="product" class="product-image img-fluid">
                    <div class="rating">
                      {% if product.rating > 0 %}
                          {% with " "|center:product.rating as range %}
                              {% for _ in range %}
                                <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-solid"></use></svg>
                              {% endfor %}
                          {% endwith %}
                      {% else %}
                          <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                          <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                          <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                          <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                          <svg width="14" height="14" viewBox="0 0 15 15"><use xlink:href="#star-outline"></use></svg>
                      {% endif %}
                    </div>
                  </a>
                  <button href="#" data-index="{{product.id}}" class="btn btn-primary w-100 mt-2 rounded-1 add-cart-mini">Add to cart</button>
                </div>
                <div class="product-content d-flex flex-column flex-md-row justify-content-between align-items-md-center">
                  <h5 class="fs-5 mt-3">
                    <a href="{% url 'product' product.slug %}">{{product.name}}</a>
                  </h5>
                  {% if product.is_sale %}
                    <span> {{ product.sale_price }} $</span>
                  {% else %}
                    <span>{{ product.price }} $</span>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
            
        </div>
      </div>
    </div>
  </section>
  
  <section id="best-sellers"
    class="best-sellers py-5 mb-5">
    <div class="container-fluid">
      <div class="d-flex flex-wrap justify-content-between align-items-center mt-5 mb-3">
        <h4 class="text-uppercase">Most Discount</h4>
        <a href="{% url 'shop' %}" class="btn-link">View All Products</a>
      </div>

      <div data-aos="fade-in">
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4">
          {% for product in d_products %}
            <div class="col">
              <div class="product-item hover-effect-slide">
                <div class="image-holder position-relative">
                  <a href="{% url 'product' product.slug %}">
                    <img src="{{product.image.url}}" alt="product" class="product-image img-fluid">
                  </a>
                  <button data-index="{{product.id}}"  class="btn btn-primary w-100 mt-2 rounded-1 add-cart-mini">Add to cart</button>
                </div>
                <div class="product-content d-flex flex-column flex-md-row justify-content-between align-items-md-center">
                  <h5 class="fs-5 mt-3">
                    <a href="{% url 'product' product.slug %}">{{product.name}}</a>
                  </h5>
                  <a  class="text-decoration-none" ><span>${{product.sale_price}}</span></a>
                  <a  class="text-decoration-line-through" ><span>${{product.price}}</span></a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

  <section class="newsletter bg-black">
    <div class="container-fluid">
      <div class="newsletter jarallax">
        <img src="{% static 'images/bg-newsletter.jpg' %}" alt="newsletter" class="jarallax-img">
      
        <div class="row py-5 justify-content-center">
          <div class="col-md-6">
            <div class="row g-5 my-4 align-items-baseline">
              <div class="col-md-7">
                <h3 class="display-4 m-0 text-md-end">Join Our Newsletter</h3>
              </div>
              <div class="col-md-5">
                <p class="fs-6 text-gray">Sign Up for our newsletter and never miss any offers</p>
              </div>
            </div>
            <div class="row mb-5">
              <div class="col-md-12">
                <div class="d-flex justify-content-center flex-row gap-0">
                  <a href="{% url 'login' %}" class="btn btn-primary text-uppercase rounded px-5">Sign Up</a>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>
    
{% endblock content %}
    